# os: linux
# osx_image: xcode9
language: node_js
sudo: required
dist: trusty
node_js:
  - v7

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - yarn install

addons:
  # firefox: latest-beta
  # chrome: stable

cache: yarn

jobs:
  include:
    - stage: Tests
      script: ./tests/test-build.js
      script: yarn run pretest
      script: yarn run test:headless
      script: travis_retry karma start --single-run --reporters mocha karma.conf.js
